/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotechquirosvargassemestreianno2018;

import File.LaptopFile;
import domain.Laptop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 * @author Steven
 * @author Eyleen
 */
public class InsertLaptop extends javax.swing.JInternalFrame {

    /**
     * Creates new form InsertLaptop
     */
    File file;
    Laptop laptop;
    LaptopFile laptopFile;
    public InsertLaptop() {
        try {
            file = new File("./Laptop.dat");
            this.laptopFile = new LaptopFile(file);
        } catch (IOException ex) {

        }
        this.setTitle("Registrar laptops");
        initComponents();
        this.buttonGroup1 = new ButtonGroup();
        this.noBtn.setSelected(true);
        this.buttonGroup1.add(yesBtn);
        this.buttonGroup1.add(noBtn);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        brandText = new javax.swing.JTextField();
        colorText = new javax.swing.JTextField();
        sizeText = new javax.swing.JTextField();
        yearText = new javax.swing.JTextField();
        yesBtn = new javax.swing.JRadioButton();
        noBtn = new javax.swing.JRadioButton();
        quantityText = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Brand:");

        jLabel2.setText("Color:");

        jLabel3.setText("Size:");

        jLabel4.setText("Year of production:");

        jLabel5.setText("Camera?");

        jLabel6.setText("Quantity:");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        yesBtn.setText("Yes");

        noBtn.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brandText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(yesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sizeText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnRegister)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(colorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yesBtn)
                    .addComponent(noBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        boolean camera;
        int code;
        //Este trycontrola la creación del archivo
        try {
            if (file.exists()) {
            } else {
                file.createNewFile();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en el procedimiento. Vuelva a intentarlo.");
        }

        //Este if le da un valor a cada radio Button
        if (yesBtn.isSelected()) {
            camera = true;
        } else {
            camera = false;
        }
//Estos if comprueba que la informacion este completa y correcta 
        if (this.brandText.getText().isEmpty() || this.colorText.getText().isEmpty()|| this.sizeText.getText().isEmpty() || this.yearText.getText().isEmpty() || this.quantityText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese toda la información solicitada.");
        } else {
            if (Integer.parseInt(this.yearText.getText()) < 1000) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese información válida");
            } else {
                try {
                    if (this.laptopFile.verifyBrand(this.brandText.getText(), Integer.parseInt(this.quantityText.getText()))) {
                        this.brandText.setText("");
                        this.colorText.setText("");
                        this.yearText.setText("");
                        this.sizeText.setText("");
                        this.quantityText.setText("");
                    } else {
                        code=Integer.parseInt(laptopFile.createCode());
                        laptop = new Laptop(Integer.parseInt(this.sizeText.getText()),this.colorText.getText(), camera, Integer.parseInt(this.quantityText.getText()),code,this.brandText.getText(), Integer.parseInt(this.yearText.getText()));
                        this.brandText.setText("");
                        this.colorText.setText("");
                        this.yearText.setText("");
                        this.sizeText.setText("");
                        this.quantityText.setText("");

                        //Este try ingresa la informacion en la posición final del archivo
                        try {
                            this.laptopFile.addEndRecord(laptop);
                        } catch (IOException ex) {
                            Logger.getLogger(InsertLaptop.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar la información. Verifique que la información esté correcta.");
                }
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandText;
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField colorText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton noBtn;
    private javax.swing.JTextField quantityText;
    private javax.swing.JTextField sizeText;
    private javax.swing.JTextField yearText;
    private javax.swing.JRadioButton yesBtn;
    // End of variables declaration//GEN-END:variables
}
