/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotechquirosvargassemestreianno2018;

import File.PhysicalFile;
import domain.Physical;
import domain.Student;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Steven
 * @author Eyleen
 */
public class InsertPhysical extends javax.swing.JInternalFrame {

    /**
     * Creates new form InsertBook
     */
    File file;
    Physical physical;
    PhysicalFile physicalFile;
    public InsertPhysical() {
        try {
            file = new File("./Physical.dat");
            this.physicalFile = new PhysicalFile(file);
        } catch (IOException ex) {

        }
        this.setTitle("Registrar libros fisicos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        authorText = new javax.swing.JTextField();
        yearText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantityText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pagesText = new javax.swing.JTextField();

        setClosable(true);

        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Name:");

        jLabel3.setText("Author:");

        jLabel4.setText("Year of publication:");

        jLabel6.setText("Quantity:");

        jLabel7.setText("Number of pages:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(registerbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pagesText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pagesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(registerbtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        String code="";
        try {
            if (file.exists()) {
            } else {
                file.createNewFile();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en el procedimiento. Vuelva a intentarlo.");
        }
        
        //Estos if comprueba que la informacion este completa y correcta 
        if (this.nameText.getText().isEmpty() || this.authorText.getText().isEmpty() || this.yearText.getText().isEmpty() || this.pagesText.getText().isEmpty() || this.quantityText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese toda la información solicitada.");
        } else {
            if (Integer.parseInt(this.yearText.getText()) < 1000) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese información válida");
            } else {
                try {
                    if (this.physicalFile.verifyName(this.nameText.getText(), Integer.parseInt(this.quantityText.getText()))) {
                        
                    } else {
                        code=physicalFile.createISBN();
                        physical = new Physical(Integer.parseInt(this.quantityText.getText()),this.nameText.getText(), this.authorText.getText(),code, Integer.parseInt(this.yearText.getText()), Integer.parseInt(this.pagesText.getText()));
                        this.nameText.setText("");
                        this.authorText.setText("");
                        this.yearText.setText("");
                        this.pagesText.setText("");
                        this.quantityText.setText("");

                        //Este try ingresa la informacion en la posición final del archivo
                        try {
                            this.physicalFile.addEndRecord(physical);
                        } catch (IOException ex) {
                            Logger.getLogger(InsertPhysical.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar la información. Verifique que la información esté correcta.");
                }
            }
        }
    }//GEN-LAST:event_registerbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField pagesText;
    private javax.swing.JTextField quantityText;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
