/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotechquirosvargassemestreianno2018;

import File.PhysicalFile;
import File.StudentFile;
import domain.Physical;
import domain.Student;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Steven
 * @author Eyleen
 */
public class SearchBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchBook
     */
    Student student = new Student();
    Physical physical = new Physical();
    PhysicalFile phyFile;
    ArrayList<Physical> allBooks = new ArrayList<Physical>();

    public SearchBook() throws IOException {
        this.phyFile = new PhysicalFile(new File ("./Physical.dat"));
        allBooks = phyFile.getAllPhysical();
        initComponents();
        idText.setText("");
        nameText.setText("");
        showInformation.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        verifyBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showInformation = new javax.swing.JTextArea();
        loanBtn = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Carne':");

        jLabel2.setText("Nombre del libro:");

        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        verifyBtn.setText("Verificar");
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });

        showInformation.setEditable(false);
        showInformation.setColumns(20);
        showInformation.setRows(5);
        jScrollPane1.setViewportView(showInformation);

        loanBtn.setText("Solicitar Prestamo");
        loanBtn.setEnabled(false);
        loanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verifyBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(loanBtn)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loanBtn)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
        File file = new File("./Student.dat");
        StudentFile studentFile;

        try {
            studentFile = new StudentFile(file);

            String c = this.idText.getText();
            if (studentFile.verifyUniversityId(c)) {
                this.loanBtn.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "El carne indicado no esta registrado, por favor registrese antes de solicitar un prestamo");
                this.loanBtn.setEnabled(false);
            }
        } catch (IOException ex) {
            Logger.getLogger(SearchBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verifyBtnActionPerformed

    private void loanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanBtnActionPerformed
       if(this.showInformation.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(this, "Primero busque un libro");
       }else{
        File file2 = new File("./Physical.dat");
        PhysicalFile physicalFile;

        try {
            physicalFile = new PhysicalFile(file2);
            int quantity = physicalFile.reduceQuantity(this.nameText.getText());
            physicalFile.update(this.nameText.getText(), quantity);
            idText.setText("");
            nameText.setText("");
            showInformation.setText("");
        } catch (IOException ex) {
            Logger.getLogger(SearchBook.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_loanBtnActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        showInformation.setText("");
        String results = "";
        
        for(int i=0; i<allBooks.size(); i++){
            if(allBooks.get(i).startsWith(this.nameText.getText())){
                results=allBooks.get(i).toString()+"\n \n";
            } 
        }
        showInformation.setText(results);
    }//GEN-LAST:event_nameTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loanBtn;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextArea showInformation;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
