/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotechquirosvargassemestreianno2018;

import File.DigitalFile;
import File.PhysicalFile;
import File.StudentFile;
import domain.Physical;
import domain.Student;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Steven
 * @author Eyleen
 */
public class SearchBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchBook
     */
    Student student = new Student();
    Physical physical = new Physical();
    PhysicalFile phyFile;
    DigitalFile digFile;

    public SearchBook() throws IOException {
        this.phyFile = new PhysicalFile(new File("./Physical.dat"));
        initComponents();
        idText.setText("");
        nameText.setText("");
        showInformation.setText("");
        this.buttonGroup1.add(this.rdbPhysical);
        this.buttonGroup1.add(this.rdbDigital);
        this.rdbPhysical.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        verifyBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showInformation = new javax.swing.JTextArea();
        loanBtn = new javax.swing.JButton();
        rdbPhysical = new javax.swing.JRadioButton();
        rdbDigital = new javax.swing.JRadioButton();
        etInformation = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("University ID:");

        jLabel2.setText("Book name:");

        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        verifyBtn.setText("Verify");
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });

        showInformation.setEditable(false);
        showInformation.setColumns(20);
        showInformation.setRows(5);
        jScrollPane1.setViewportView(showInformation);

        loanBtn.setText("Make the loan");
        loanBtn.setEnabled(false);
        loanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanBtnActionPerformed(evt);
            }
        });

        rdbPhysical.setText("Physical");

        rdbDigital.setText("Digital");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(loanBtn)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbPhysical)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbDigital))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verifyBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyBtn)
                    .addComponent(etInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbPhysical)
                    .addComponent(rdbDigital))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loanBtn)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
        File file = new File("./Student.dat");
        StudentFile studentFile;

        try {
            studentFile = new StudentFile(file);

            String c = this.idText.getText();
            if (studentFile.verifyUniversityId(c)) {
                this.loanBtn.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "El carne indicado no esta registrado, por favor registrese antes de solicitar un prestamo");
                this.loanBtn.setEnabled(false);
            }
        } catch (IOException ex) {
            Logger.getLogger(SearchBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verifyBtnActionPerformed

    private void loanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanBtnActionPerformed
        if (this.showInformation.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Primero busque un libro");
        } else {
            if (rdbPhysical.isSelected()) {
                File file2 = new File("./Physical.dat");
                PhysicalFile physicalFile;
                try {
                    physicalFile = new PhysicalFile(file2);
                    int quantity = physicalFile.reduceQuantity(this.nameText.getText());
                    physicalFile.update(this.nameText.getText(), quantity);
                    JOptionPane.showMessageDialog(this, "Prestamo realizado exitosamente");
                    idText.setText("");
                    nameText.setText("");
                    showInformation.setText("");
                    etInformation.setText("");
                } catch (IOException ex) {
                    Logger.getLogger(SearchBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (rdbDigital.isSelected()) {
                File file2 = new File("./Digital.dat");
                DigitalFile digitalFile;
                try {
                    digitalFile = new DigitalFile(file2);
                    JOptionPane.showMessageDialog(this, "Prestamo realizado exitosamente");
                    idText.setText("");
                    nameText.setText("");
                    showInformation.setText("");
                    etInformation.setText("");
                } catch (IOException ex) {
                    Logger.getLogger(SearchBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_loanBtnActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        showInformation.setText("");
        String results = "";

        if (rdbPhysical.isSelected()) {
            File file2 = new File("./Physical.dat");
            PhysicalFile physicalFile;
            try {
                physicalFile = new PhysicalFile(file2);
                for (int i = 0; i < physicalFile.getAllPhysical().size(); i++) {
                    if (physicalFile.getAllPhysical().get(i).startsWith(this.nameText.getText())) {
                        results += physicalFile.getAllPhysical().get(i).toString() + "\n \n";
                    }
                    showInformation.setText(results);
                }
            } catch (IOException ex) {
                Logger.getLogger(SearchBook.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (rdbDigital.isSelected()) {
            File file2 = new File("./Digital.dat");
            DigitalFile digitalFile;
            try {
                digitalFile = new DigitalFile(file2);

                for (int i = 0; i < digitalFile.getAllDigital().size(); i++) {
                    if (digitalFile.getAllDigital().get(i).startsWith(this.nameText.getText())) {
                        results += digitalFile.getAllDigital().get(i).toString() + "\n \n";
                    }
                    showInformation.setText(results);
                }
            } catch (IOException ex) {
                Logger.getLogger(SearchBook.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_nameTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etInformation;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loanBtn;
    private javax.swing.JTextField nameText;
    private javax.swing.JRadioButton rdbDigital;
    private javax.swing.JRadioButton rdbPhysical;
    private javax.swing.JTextArea showInformation;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
